# Generated by Django 3.2.5 on 2022-06-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('page', models.URLField(blank=True)),
                ('picture', models.URLField(blank=True)),
            ],
        ),
    ]
